name: easybeam_flutter
description: A Flutter SDK for Easybeam AI platform
version: 2.0.0
homepage: https://github.com/easybeamai/easybeam_flutter

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  fetch_client: ^1.1.2
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.13

flutter:
