name: Flutter Tests

on:
  pull_request:
    branches: [main, develop]

jobs:
  test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "4.0.0"
          channel: "stable"
      - name: Install dependencies
        run: flutter pub get
      - name: Generate mocks
        run: flutter pub run build_runner build --delete-conflicting-outputs
      - name: Run tests
        run: flutter test
